// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class AdminSetting
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Description { get; set; }

    public string ValString { get; set; }

    public int? ValInt { get; set; }

    public decimal? ValDecimal { get; set; }

    public DateTime? ValDatetime { get; set; }

    public bool? ValBit { get; set; }

    public DateTime Ts { get; set; }
}