// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class AmortPlan
{
    public string DocumentId { get; set; }

    public int ContractId { get; set; }

    public string ClaimType { get; set; }

    public string CurrencyCode { get; set; }

    public DateOnly ClaimDate { get; set; }

    public DateOnly ClaimDueDate { get; set; }

    public int ClaimPeriod { get; set; }

    public decimal NetAmount { get; set; }

    public decimal InterestAmount { get; set; }

    public decimal TaxAmount { get; set; }

    public decimal OtherAmount { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal PaidAmount { get; set; }

    public decimal DueAmount { get; set; }

    public DateTime Ts { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Currency CurrencyCodeNavigation { get; set; }
}