// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Contract
{
    public int ContractId { get; set; }

    public string ContractNumber { get; set; }

    public int CustomerId { get; set; }

    public string Description { get; set; }

    public decimal ContractValue { get; set; }

    public decimal TaxValue { get; set; }

    public decimal InterestRate { get; set; }

    public string CurrencyCode { get; set; }

    public decimal TaxRate { get; set; }

    public string ActivityStatus { get; set; }

    public DateOnly EnteredDate { get; set; }

    public DateOnly? ActivationDate { get; set; }

    public int Duration { get; set; }

    public int EmployeeId { get; set; }

    public DateTime Ts { get; set; }

    public virtual ICollection<AmortPlan> AmortPlans { get; set; } = new List<AmortPlan>();

    public virtual Currency CurrencyCodeNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}