// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Country
{
    public string CountryCode { get; set; }

    public string CountryName { get; set; }

    public bool EuMember { get; set; }

    public DateTime Ts { get; set; }

    public virtual ICollection<Currency> Currencies { get; set; } = new List<Currency>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}