// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Currency
{
    public string CurrencyCode { get; set; }

    public string Name { get; set; }

    public string InternationalCode { get; set; }

    public string CountryCode { get; set; }

    public bool Inactive { get; set; }

    public DateTime Ts { get; set; }

    public virtual ICollection<AmortPlan> AmortPlans { get; set; } = new List<AmortPlan>();

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual Country CountryCodeNavigation { get; set; }

    public virtual ICollection<ExchangeRate> ExchangeRateCurrencyFromNavigations { get; set; } = new List<ExchangeRate>();

    public virtual ICollection<ExchangeRate> ExchangeRateCurrencyToNavigations { get; set; } = new List<ExchangeRate>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}