// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string ShortName { get; set; }

    public string FullName { get; set; }

    public string RegistrationNumber { get; set; }

    public string TaxNumber { get; set; }

    public string Street { get; set; }

    public string PostalCode { get; set; }

    public string CountryCode { get; set; }

    public string Email { get; set; }

    public string CustomerType { get; set; }

    public int? AssignedEmployeeId { get; set; }

    public bool Inactive { get; set; }

    public DateTime Ts { get; set; }

    public virtual Employee AssignedEmployee { get; set; }

    public virtual ICollection<Contract> Contracts { get; set; } = new List<Contract>();

    public virtual Country CountryCodeNavigation { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}