// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Department
{
    public int DepartmentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime Ts { get; set; }

    public virtual ICollection<EmployeesDepartment> EmployeesDepartments { get; set; } = new List<EmployeesDepartment>();
}