// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class EmployeesDepartment
{
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public int DepartmentId { get; set; }

    public DateTime ActiveFrom { get; set; }

    public DateTime? ActiveTo { get; set; }

    public DateTime Ts { get; set; }

    public virtual Department Department { get; set; }

    public virtual Employee Employee { get; set; }
}