// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class ExchangeRate
{
    public string CurrencyFrom { get; set; }

    public string CurrencyTo { get; set; }

    public decimal ExchangeRate1 { get; set; }

    public DateOnly ExchangeRateDate { get; set; }

    public DateTime Ts { get; set; }

    public virtual Currency CurrencyFromNavigation { get; set; }

    public virtual Currency CurrencyToNavigation { get; set; }
}