// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public int CustomerId { get; set; }

    public DateOnly InvoiceIssueDate { get; set; }

    public DateOnly DueDate { get; set; }

    public string CurrencyCode { get; set; }

    public decimal NetAmount { get; set; }

    public decimal TaxAmount { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal TaxRate { get; set; }

    public string DocumentId { get; set; }

    public int? ContractId { get; set; }

    public DateTime Ts { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Currency CurrencyCodeNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}