// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidatesAPI.Entities;

public partial class Payment
{
    public int PaymentId { get; set; }

    public DateOnly PaymentDate { get; set; }

    public decimal PaymentAmount { get; set; }

    public string CurrencyCode { get; set; }

    public string DocumentId { get; set; }

    public int? InvoiceId { get; set; }

    public int? CustomerId { get; set; }

    public DateTime Ts { get; set; }

    public virtual Currency CurrencyCodeNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Invoice Invoice { get; set; }
}